# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'ubuntu-20.04'
  
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**\Home.sln'

steps:
- script: |
    dotnet build Home.sln --configuration $(buildConfiguration)
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Home.Core.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'vs.alexsalisbury'
    repository: 'shycloud'
    command: 'buildAndPush'
    Dockerfile: '**/Shy.Cloud/Dockerfile'
