# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**\Home.sln'
  disable.coverage.autogenerate: 'true' # because we overwrite the coverage report generation

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime
- task: NuGetToolInstaller@1
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-reportgenerator-globaltool -g
  displayName: Install ReportGenerator tool
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install coverlet.console -g
  displayName: Install Coverlet.Console tool
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Home.sln'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/Home.sln'
    arguments: '--collect:"XPlat Code Coverage"'

- script: |
    mkdir .\reports
    reportgenerator.exe -reports:$(Agent.TempDirectory)/**/*.xml -targetdir:reports -reporttypes:"HTMLInline;HTMLChart"
  displayName: Create coverage reports in html format to be displayed in AzureDevOps
- script: |
    reportgenerator.exe -reports:$(Agent.TempDirectory)/**/*.xml -targetdir:reports -reporttypes:"cobertura"
  displayName: Create coverage reports in xml format to be used for summary
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(system.defaultworkingdirectory)\reports\Cobertura.xml'
    reportDirectory: '$(system.defaultworkingdirectory)\reports'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Home.Core.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'