# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'windows-2019'
  
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**\Home.sln'

steps:
- script: |
    dotnet build Home.sln --configuration $(buildConfiguration)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'