# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**\Home.sln'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '420296a8-b9e3-4cf7-b3bb-03b6a14bc54d/b4fdf3af-3118-44f7-941e-3cb32243bd36'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Home.sln'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/test/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[Home.*]*" /p:Exclude="[*Tests]*"'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(Build.SourcesDirectory)/tests/**/coverage.cobertura.xml

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Home.Core.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'